[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "idmt_tool"
version = "1.0.0"
description = "IEC IDMT Trip Time Calculator"
authors = [{ name = "Godwin" }]
dependencies = ["ttkbootstrap"]

[tool.setuptools]
packages = ["idmt_tool"]

